### PR TITLE
Broke out network bottleneck large card into several cards to break t…

### PR DESCRIPTION
**Pull request by harrystaley**
…he concepts out better.

### CODE REVIEW

**Review by wyohm — COMMENTED** [review]
The content seems fine. I would like to keep the lesson and section information like the other cards have (e.g. "`<h1>Lesson 5: Router Design and Algorithms</h1>\n<h2>\n  The Challenges Routers Face\n</h2>`" at the beginning). I study all my OMSCS cards from the various courses together, so it helps me understand the context of the question. Plus for anyone learning the material, it helps them know where to look if they need additional information. Also the tags on the note.

Using the "create copy" feature in Anki should help make that easier.

**Comment by harrystaley** [comment]
So the lesson and section on this card are already there in the title section. Otherwise, it is big and takes up a ton of space. Also, I added a line break between the title and the question so that there is some visual space between the title and the question being asked. I don't have an issue adding the title to the card through.

**Comment by wyohm** [comment]
It's the established style for this and the other decks I've created. Changing the style should be a separate discussion (but one that I'm not generally inclined toward).

**Comment by harrystaley** [comment]
That is fine. The style takes up a TON of screen real estate duplicating information that is already available in the deck title and the cards themselves have entire paragraphs of information on them which could be broken up. I want to contribute to your deck, but there seems to be no discussion available.

**Comment by harrystaley** [comment]
I also added several things to make your repo more anti fragile.

**Pull request closed without merging**
