### PR TITLE
updated readme to be easier on screen readers

### PR DESCRIPTION
**Pull request by harrystaley**

### CODE REVIEW

**Comment by harrystaley** [comment]
I plan on contributing quite a bit to this repository. I am a huge fan of Anki!

**Comment by harrystaley** [comment]
Added several cards for week 3 specifically.

**Comment by wyohm** [comment]
Thanks for exporting with CrowdAnki. However the diff on this is huge (+3,567 −7,884 ), making it difficult to see what's actually happening. I'm not quite sure why that is. Did you make any structural changes to the deck (e.g. moving all the notes into a single deck)?

BTW, I noticed some small image files that seem to come from LaTeX. You should try the Mathjax rendering. It uses the same markup, but renders dynamically, rather than creating images files.

**Comment by harrystaley** [comment]
If you have a preference please put it in the readme. Otherwise, it discourages others from contributing when they spend lots of time creating things. I organized things into a single deck where you can click on individual study weeks or even the exam. For example Networks Course::Exam 1::Week 1 - Topic. This way you can select what you want to study. I am legally blind and natively use LaTex every day. My screen reader has no issues with reading Latex. Many of the cards are not usable by my screen reader and as such, I had to recreate them so that the question could be asked without the huge image.

**Comment by harrystaley** [comment]
I am happy to use MathJax if that is what you would prefer.

**Comment by wyohm** [comment]
I can't merge as is. The main issue is that because of the restructuring (I think), I can't see what's going on in the diff. Also, with 3,567 new lines and 7,884 removed lines, that's 4,317 lines deleted net.

I appreciate your contribution, but right now it's not possible to see what's being contributed, and appears to remove a lot of the work I did. If you're able to make a commit that has diffs that are readable, I could review and merge (e.g. the changes to the Readme were fine). I'm not sure what would be involved in doing that; I'm still learning the workflow using CrowdAnki too. If that's not possible/a lot of work, you're of course welcome to maintain your own fork.

**Comment by harrystaley** [comment]
I added a ton of cards i also revised almost all of the existing cards to make them accessible via screen reader.Harry Staley(330) ***@***.*** Feb 10, 2023, at 12:59, wyohm ***@***.***> wrote:﻿
I can't merge as is. The main issue is that because of the restructuring (I think), I can't see what's going on in the diff. Also, with 3,567 new lines and 7,884 removed lines, that's 4,317 lines deleted net.
I appreciate your contribution, but right now it's not possible to see what's being contributed, and appears to remove a lot of the work I did. If you're able to make a commit that has diffs that are readable, I could review and merge (e.g. the changes to the Readme were fine). I'm not sure what would be involved in doing that; I'm still learning the workflow using CrowdAnki too. If that's not possible/a lot of work, you're of course welcome to maintain your own fork.

**Pull request closed without merging**
