### PR TITLE
Wherever possible converted image questions to normal questions that could be used with screen readers and changed all Latex equations to MathJax per your request.

### PR DESCRIPTION
**Pull request by harrystaley**

### CODE REVIEW

**Comment by wyohm** [comment]
Hi Harry, thanks for your contribution. However, like before, it is too divergent to accept. The path of the exported "deck.json" is different. As far as I can tell, none of the notes I created are present (all have been deleted). There were 624 notes in the deck in my last commit, but your PR has only 214.

**Comment by harrystaley** [comment]
These changes only affect the Networks course. I have not made any other changes to the decks included.

**Comment by wyohm** [comment]
Yes, I see that. It looks like you added the course number (which is incorrect, the course number is CS6250, not CS250) to the deck name, so the export changed from "GA_Tech_OMSCS__Computer_Networks/deck.json" to "GA_Tech_OMSCS__CS250_Computer_Networks/deck.json".

Even when I consider the name change, it appears the number of notes I mentioned before is still an issue. I don't think the notes I created are in your export.

**Comment by harrystaley** [comment]
As I said, the notes you created have a lot of images that I converted to text-based cards so that screen readers can use them. For example, the OSI model image was converted to a dozen text-based cards.

**Comment by harrystaley** [comment]
So I only changed the network cards. The other notes have NOT changed.

**Comment by wyohm** [comment]
I think I found the root issue. Did you start with this deck from AnkiWeb?
https://ankiweb.net/shared/info/436247740

That is not my deck.

**Comment by harrystaley** [comment]
Ok then I will merge your deck.

**Comment by wyohm** [comment]
Merge meaning include the notes from that other deck plus the ones I created? I don't think that's a good idea. The other deck is someone else's work, and it's available if people want to use it (possibly using the one I created as well). Plus, I think there's going to be a lot of redundancy between the two of them.

**Comment by harrystaley** [comment]
So the old deck notes have been removed, and only my contributions remain.

**Comment by harrystaley** [comment]
> Merge meaning include the notes from that other deck plus the ones I created? I don't think that's a good idea. The other deck is someone else's work, and it's available if people want to use it (possibly using the one I created as well). Plus, I think there's going to be a lot of redundancy between the two of them.

I am de-duping the decks with a preference for your chards.

**Comment by harrystaley** [comment]
So it would be helpful if you gave some concrete criteria for contributing to the repo.

**Comment by harrystaley** [comment]
How about this I will kill ALL of my changes and only have yours and just leave them as they are. I want to contribute but I have no guidelines as to what changes will be accepted or not.

**Comment by wyohm** [comment]
Just starting from the right base deck was a huge step forward. The PR before that point would have deleted all my work.

I think it's usually expected that you propose a change (probably in the form of creating an "issue") before doing a lot of work and making a PR. It's difficult to predict what changes someone might want to make and outline what will and won't be accepted. But in general, I'm most interested in adding newly contributed cards. Deletions of existing notes won't be accepted unless there's a good reason. Sweeping changes like changing the styling (making changes to the note type) of all the cards should be avoided or check first. There are established note types (e.g. "OMSCS Basic", "OMSCS Cloze") and style (shows lesson and subsection as headers), try to stick with that.

PRs should be atomic so they can be reviewed individually. That doesn't mean there needs to be a separate PR for every tiny change, but things that make sense for separate PRs might be "update contribution guidelines for README", "add notes for quiz in lesson 1"...

**Pull request closed without merging**
